version: '3.1'

services:

  postgres:
    image: postgres:9.6
    container_name: "postgres-v12"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gitevent
    volumes:
      - ./config/:/docker-entrypoint-initdb.d


